### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by klequis** [inrupt/solid-ui-react-example-project#22]
Hi.

I cloned the example repo and follwed the directions.

I'm using Chrome on Ubuntu 20.04. It is my first time trying anything Solid related.

Problem: I'm getting an error when loging in

I start the app using

```
npm ci && npm run dev
```

There is one warning of note in the terminal:

```
warn  - ./node_modules/@inrupt/solid-client/dist/index.es.js
Module not found: Can't resolve 'solid-auth-client' in '/home/klequis/just-looking/solid-ui-react-example-project/node_modules/@inrupt/solid-client/dist'
```

Put https://localhost:3000 in the browser

Chrome puts up a page saying "Your connection is not private" with an 'Advanced' button

- Click "Advanced"
- Click "Proceed to localhost (unsafe)"

- Enter https://inrupt.net for identity provider and click LOG IN

- enter username & password
- Click Log In

The result is the error below.

ERROR

Unhandled Runtime Error
Error: URL not found for given property

Call Stack
C
node_modules/@inrupt/solid-ui-react/dist/index.js (1:6413)
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (14803:0)
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js (17482:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (18596:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (188:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (237:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (292:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (23203:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (22154:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (22130:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (21756:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (11089:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (653:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11039:0)
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js (11084:0)
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js (11072:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (22883:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (653:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11039:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (22820:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (22699:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (597:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (552:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (164:0)

**Comment by Vinnl** [comment]
Hi @klequis and @dotmpe, sorry for taking so long before getting back to you. It looks like this is an issue in upstream solid-ui-react, which was already reported here: https://github.com/inrupt/solid-ui-react/issues/250 That issue will be updated when the problem has been resolved, so I'll close this one and would recommend subscribing to that.

If you believe this issue should not be closed, feel free to re-open with a comment on why :)
